spree-master/backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  root :to => 'home#index'

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :image_settings

    resources :orders, :except => [:show] do
      member do
        put :fire
        get :fire
        post :resend
        get :open_adjustments
        get :close_adjustments
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments do
        member do
          get :toggle_state
        end
      end
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, :except => [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_movements
    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates
    resource  :tax_settings

    resources :trackers
    resources :payment_methods
    resource :mail_method, :only => [:edit, :update] do
      post :testmail, :on => :collection
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin
end

spree-master/backend/app/controllers/spree/admin/states_controller.rb
module Spree
  module Admin
    class StatesController < ResourceController
      belongs_to 'spree/country'
      before_filter :load_data

      def index
        respond_with(@collection) do |format|
          format.html
          format.js { render :partial => 'state_list' }
        end
      end

      protected

        def location_after_save
          admin_country_states_url(@country)
        end

        def collection
          super.order(:name)
        end

        def load_data
          @countries = Country.order(:name)
        end
    end
  end
end

spree-master/backend/app/views/spree/admin/states/_form.html.erb
<div data-hook="admin_state_form_fields" class="row">
  <div class="alpha six columns">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, :class => 'fullwidth' %>
    <% end %>
  </div>
  <div class="omega six columns">
    <%= f.field_container :abbr do %>
      <%= f.label :abbr, Spree.t(:abbreviation) %>
      <%= f.text_field :abbr, :class => 'fullwidth' %>
    <% end %>
  </div>
</div>

spree-master/backend/app/views/spree/admin/states/_state_list.html.erb
<div id="new_state" data-hook></div>

<table class="index" id='listing_states' data-hook>
  <colgroup>
    <col style="width: 70%" />
    <col style="width: 15%" />
    <col style="width: 15%" />
  </colgroup>
  <thead>
    <tr data-hook="states_header">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:abbreviation) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @states.each do |state| %>
      <tr id="<%= spree_dom_id state %>" data-hook="states_row" class="<%= cycle('odd', 'even')%>">
        <td><%= state.name %></td>
        <td class="align-center"><%= state.abbr %></td>
        <td class="actions">
          <%= link_to_with_icon 'icon-edit', Spree.t(:edit), edit_admin_country_state_url(@country, state), :no_text => true %>
          <%= link_to_delete state, :no_text => true %>
        </td>
      </tr>
    <% end %>
    <% if @states.empty? %>
      <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
    <% end %>
  </tbody>
</table>

spree-master/backend/app/views/spree/admin/states/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_state) %> <i class="icon-arrow-right"></i> <%= @state.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_states_list), spree.admin_country_states_url(@country), :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @state } %>

<%= form_for [:admin, @country, @state] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

spree-master/backend/app/views/spree/admin/states/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:states) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_state_link">
    <%= button_link_to Spree.t(:new_state), new_admin_country_state_url(@country), { :remote => true, :icon => 'icon-plus', :id => 'new_state_link' } %>
  </li>
<% end %>

<div data-hook="country" class="field row">
  <%= label_tag :country, Spree.t(:country) %>
  <select id="country" class='observe_field select2 fullwidth' data-base-url="<%=admin_states_path(:format => :js) %>?country_id=" data-update="#state-list">
  <%= options_from_collection_for_select(@countries, :id, :name, @country.id) %>
  </select>
</div>

<%= image_tag 'spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>

<div id="state-list" data-hook>
  <%= render :partial => 'state_list'%>
</div>

spree-master/backend/app/views/spree/admin/states/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @state } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_state) %>
<% end %>

<%= form_for [:admin, @country, @state] do |f| %>
  <fieldset>
    <legend><%= Spree.t(:new_state) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

spree-master/backend/app/views/spree/admin/states/new.js.erb
$("#new_state").html("<%= escape_javascript(render :template => 'spree/admin/states/new', :formats => [:html], :handlers => [:erb]) %>");
$("#new_state_link").parent().hide();